AllCops:
  TargetRubyVersion: 3.X
  NewCops: enable
  SuggestExtensions: false

Style/ClassVars:
  Enabled: false

Metrics/BlockLength:
  AllowedMethods: ['describe', 'context']

Metrics/ClassLength:
  Enabled: false

Layout/LineLength:
  Exclude:
    - lib/cli/command_interface.rb

Metrics/MethodLength:
  Exclude:
    - lib/cli/command_interface.rb
    - lib/models/train.rb
    - lib/modules/accessors.rb

Metrics/AbcSize:
  Exclude:
    - lib/cli/command_interface.rb